"""Protocol for AI agent backends (Devin, future alternatives)."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from vuln_remediation.models import DevinMessage as AgentMessage
from vuln_remediation.models import DevinSession as AgentSession
from vuln_remediation.models import DevinSessionStatus as AgentSessionStatus


@runtime_checkable
class AgentClient(Protocol):
    """Interface for AI agent backends."""

    async def create_session(self, prompt: str, *, playbook_id: str | None = None) -> AgentSession: ...
    async def get_session(self, session_id: str) -> AgentSessionStatus: ...
    async def send_message(self, session_id: str, message: str) -> None: ...
    async def get_messages(self, session_id: str) -> list[AgentMessage]: ...
    async def get_attachments(self, session_id: str) -> list[dict[str, str]]: ...
    async def download_attachment(self, url: str) -> bytes: ...
    async def close_session(self, session_id: str) -> None: ...
    async def close(self) -> None: ...
